title:              Mqt 2022
email:              mqt2022@gmail.com
description:        Description of mqt2022
author:             mqt2022
baseurl:            ""
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   mqt2022Twitter
github_username:    mqt2022GitHub
facebook_username: 
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
